[DIRETORIOS]
sup=/u3
supsul=/u5
home=/home
cibrasec_aceite=/u3/cibrasec_aceite
cohabct_edital=/sys5/u2/cohabct_edital
conversao_cibra=/sys5/u3/cibrasec/suporte/conversao_cibra
u2=/sys5/u2
u4=/sys5/u4
u5=/sys5/u5
u3=/sys5/u3
testaver=/u3/testaver/dados
suplarcky=/u3/larcky/suporte
suptetto=/u3/tetto/suporte
supcfiae=/u3/cfiae/suporte
supcohapar=/u5/cohapar/suporte
supcohabct=/u5/cohabct/suporte
suppiemonte=/u5/piemonte/suporte
supcohabac=/u3/cohabac/suporte
supband=/u3/band/suporte
supcibrasec=/u3/cibrasec/suporte
supcobansa=/u3/cobansa/suporte
supsfi=/u3/sfi/suporte
supbrj=/u3/brj/suporte
[ENV]
TMP=/var/tmp
