#! /bin/sh

# Source function library.
. /etc/rc.d/init.d/functions

# Get config.
. /etc/sysconfig/network

PORT=3389
LOUNCHER=/usr/bin/launcher

[ -f $LOUNCHER ] || exit 0

# See how we were called.
case "$1" in
  start)
	. /etc/profile
        umask 002
        export LD_LYBRARY_PATH=/usr/local/kylix/bin:/home/oracle/lib	
	gprintf "Starting %s services: " "LOUNCHER"
	$LOUNCHER $PORT 2> /var/log/louncher.err > /var/log/louncher.log &
#	$LOUNCHER $PORT 2> /var/log/launcher.err > /dev/null &
        echo $$ > /var/run/launcher.pid
	echo
	;;
  stop)

	gprintf "Stopping %s services: " "LOUNCHER"
	killproc launcher

	echo
	;;
  status)
	status launcher 
	;;
  reload)
	/usr/bin/huplauncher 
	;;
  restart)
	louncherd stop 
	louncherd start
	;;
  *)
	echo "Usage: louncherd {start|stop|status|restart|reload}"
	exit 1
esac

exit 0
